spring.config.import=optional:file:.env[.properties]

spring.application.name=satchel

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

satchel.financial.accrual-period=60000
satchel.financial.assets.supported=ETH_TEST5,USDC_ETH_TEST5_AN74,AVAXTEST,ETH-AETH_SEPOLIA,AMOY_POLYGON_TEST,BNB_TEST
# Interest rate on loans
satchel.financial.assets.interest-rate={'ETH_TEST5':0.05,'USDC_ETH_TEST5_AN74':0.05,'AVAXTEST':0.05,'ETH-AETH_SEPOLIA':0.05,'AMOY_POLYGON_TEST':0.05,'BNB_TEST':0.05}
satchel.financial.assets.ltv={'ETH_TEST5':0.8,'USDC_ETH_TEST5_AN74':0.8,'AVAXTEST':0.8,'ETH-AETH_SEPOLIA':0.8,'AMOY_POLYGON_TEST':0.8,'BNB_TEST':0.8}
satchel.financial.assets.fin-margin={'ETH_TEST5':0.1,'USDC_ETH_TEST5_AN74':0.1,'AVAXTEST':0.1,'ETH-AETH_SEPOLIA':0.1,'AMOY_POLYGON_TEST':0.1,'BNB_TEST':0.1}
satchel.financial.assets.deposit-sweep-minimum={'ETH_TEST5':0.01,'USDC_ETH_TEST5_AN74':0.01,'AVAXTEST':0.01,'ETH-AETH_SEPOLIA':0.01,'AMOY_POLYGON_TEST':0.01,'BNB_TEST':0.01}
