package com.jejo.satchel.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import com.jejo.satchel.dto.SignupRequest;
import com.jejo.satchel.model.User;

@Mapper(componentModel = "spring")
public interface AuthMapper {
	
	AuthMapper INSTANCE = Mappers.getMapper(AuthMapper.class);
	
	@Mapping(target = "id", ignore = true) // Ignore ID as it will be generated by the database
	@Mapping(target = "verified", ignore = true) // Default to false for new users
	User toUserEntity(SignupRequest signupRequest);
}
